name: Terraform Deploy

on:
  push:
    branches:
      - dev  
  pull_request:
    branches:
      - dev  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
        
      - name: Run tests
        run: |
          pip install -r requirements.txt
          cd test
          pytest current_time_test.py

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Refresh Terraform state
        run: |
          cd terraform
          terraform refresh

      - name: Validate Terraform configuration
        run: |
          cd terraform
          terraform validate

      - name: Deploy Terraform
        run: |
          cd terraform
          terraform plan -out=tfplan
          terraform apply -input=false tfplan

      - name: Cleanup Terraform plan
        run:  |
          cd terraform
          rm -rf tfplan*
